apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "looking-glass.fullname" . }}
  namespace: {{ include "looking-glass.namespace" . }}
  labels:
    {{- include "looking-glass.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  CANVAS_WIDTH: {{ .canvasWidth | quote }}
  CANVAS_HEIGHT: {{ .canvasHeight | quote }}
  DEFAULT_TRANSLATE_LANGUAGE: {{ .defaultTranslateLanguage | quote }}
  PORT: {{ .port | quote }}
  {{- end }}
