{{- $fullName := include "looking-glass.fullname" . -}}
{{- $namespace := include "looking-glass.namespace" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "looking-glass.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secrets }}
  IMAGE_MODEL: {{ .imageModel | quote }}
  TRANSLATION_MODEL: {{ .translationModel | quote }}
  IMAGE_MODEL_URL: {{ .imageModelUrl | quote }}
  TRANSLATION_MODEL_URL: {{ .translationModelUrl | quote }}
  {{- end }}
  {{- with .Values.secrets }}
  {{- if .oauth2ClientId }}
  OAUTH2_CLIENT_ID: {{ .oauth2ClientId | quote }}
  {{- end }}
  {{- if .oauth2ClientSecret }}
  OAUTH2_CLIENT_SECRET: {{ .oauth2ClientSecret | quote }}
  {{- end }}
  {{- if .oauth2RedirectUri }}
  OAUTH2_REDIRECT_URI: {{ .oauth2RedirectUri | quote }}
  {{- end }}
  {{- if .oauth2Issuer }}
  OAUTH2_ISSUER: {{ .oauth2Issuer | quote }}
  {{- end }}
  {{- if .oauth2Scopes }}
  OAUTH2_SCOPES: {{ .oauth2Scopes | quote }}
  {{- end }}
  {{- if .oauth2AuthorizeUrl }}
  OAUTH2_AUTHORIZE_URL: {{ .oauth2AuthorizeUrl | quote }}
  {{- end }}
  {{- if .oauth2TokenUrl }}
  OAUTH2_TOKEN_URL: {{ .oauth2TokenUrl | quote }}
  {{- end }}
  {{- if .oauth2JwksUrl }}
  OAUTH2_JWKS_URL: {{ .oauth2JwksUrl | quote }}
  {{- end }}
  {{- if .sessionSecretKey }}
  SESSION_SECRET_KEY: {{ .sessionSecretKey | quote }}
  {{- end }}
  {{- if .redisUrl }}
  REDIS_URL: {{ .redisUrl | quote }}
  {{- end }}
  {{- if .accessCodeTtl }}
  ACCESS_CODE_TTL: {{ .accessCodeTtl | quote }}
  {{- end }}
  {{- end }}
