{{- $fullName := include "looking-glass.fullname" . -}}
{{- $namespace := include "looking-glass.namespace" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "looking-glass.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secrets }}
  IMAGE_MODEL: {{ .imageModel | quote }}
  TRANSLATION_MODEL: {{ .translationModel | quote }}
  IMAGE_MODEL_URL: {{ .imageModelUrl | quote }}
  TRANSLATION_MODEL_URL: {{ .translationModelUrl | quote }}
  {{- end }}
