import io
import json
import re
from typing import List, Tuple

from PIL import Image
from pydantic_ai import BinaryContent

from app.common import logger, IMAGE_MODEL, LABEL_PROMPT, LLM_BASE_URL
from app.dependencies import build_chat_agent
from app.schema import TextBoundingBox, Label, AnnotationResponse


async def prepare_image_for_deepseek_ocr(upload_file: bytes) -> Image.Image:
    """
    Prepare an image for DeepSeek-OCR vLLM inference.
    Resizes image to maximum 1024x1024 while keeping aspect ratio.
    """
    # Read the uploaded file
    image_data = io.BytesIO(upload_file)

    # Open and convert to RGB
    img = Image.open(image_data)

    # Convert to RGB if necessary
    if img.mode != 'RGB':
        if img.mode in ('RGBA', 'LA', 'P'):
            # Create white background for transparency
            background = Image.new('RGB', img.size, (255, 255, 255))
            if img.mode == 'P':
                img = img.convert('RGBA')
            if img.mode == 'RGBA':
                background.paste(img, mask=img.split()[-1])
            else:
                background.paste(img)
            img = background
        else:
            img = img.convert('RGB')

    # Resize image to maximum 1024x1024 while preserving aspect ratio
    max_size = 512
    img.thumbnail((max_size, max_size), Image.Resampling.LANCZOS)

    # Convert to grayscale
    img = img.convert("L")

    # Return PIL Image directly - no resizing
    output = io.BytesIO()
    img.save(output, format='JPEG', quality=90)
    # Return the bytes
    return output.getvalue()

def _get_image_size(image: Image.Image) -> Tuple[int, int]:
    """
    Retrieve the dimensions of the given image.

    This function extracts the width and height of an image object and returns them as a tuple.
    It is designed to work with PIL Image objects and provides a simple interface to access
    image size information.

    Parameters
    ----------
    image : Image.Image
        The PIL Image object from which to retrieve the size.

    Returns
    -------
    Tuple[int, int]
        A tuple containing the width and height of the image in pixels.
    """


def parse_text_with_boxes(text: str) -> List[Label]:
    """ Parse a string in the format: [[x1, y1, x2, y2]]\n [[x3, y3, x4, y4]]\n...
    Returns an AnnotationResponse with labels containing text and coordinates.
    """
    labels: List[Label] = []
    lines = text.strip().split('\n')
    
    for line in lines:
        pattern = r'(<\|ref\|>(.*?)<\|/ref\|><\|det\|>(.*?)<\|/det\|>)'
        matches = re.findall(pattern, line, re.DOTALL)
        try:
            _, text, box_str = matches[0]
        except:
            continue

        try:
            box = json.loads(box_str)
            coords = [x for x in box[0]]
            if len(coords) != 4:
                continue  # Skip if not exactly 4 coordinates

            x1, y1, x2, y2 = coords

            # Create label
            label = Label(
                x1=x1 / 999,
                y1=y1 / 999,
                x2=x2 / 999,
                y2=y2 / 999,
                text=text
            )
            labels.append(label)
        except:
            continue
    # Create response with empty coordinate mapping (since not provided in input)
    return labels

async def _extract_labels_from_image(binary_image: bytes) -> AnnotationResponse:
    """Extract text labels from an image using a labeler agent."""
    logger.info("Starting label extraction from image")

    logger.info("Image opened")
    # Scale image for processing
    scaled_image = await prepare_image_for_deepseek_ocr(binary_image)
    # Fallback to LLM-based approach
    labeler = build_chat_agent(
        f"{LLM_BASE_URL}/{IMAGE_MODEL}/v1",
        IMAGE_MODEL,
        # "<image>\n<|grounding|>Locate <|ref|>text </|ref|>.",
        LABEL_PROMPT,
        output_type=list[Label],
        settings=None,
    )
    # Extract labels
    labels = await labeler.run([
        BinaryContent(
            data=scaled_image,
            media_type="image/jpeg"
        )
    ])

    # result = parse_text_with_boxes(labels.output)
    result: list[Label] = labels.output

    for e in result:
        e.x1 /= 999.0
        e.x2 /= 999.0
        e.y1 /= 999.0
        e.y2 /= 999.0
    return AnnotationResponse(
        labels=result
    )


x1_i = 0
y1_i = 1
x2_i = 2
y2_i = 3


async def _extract_labels_from_bounding_boxes(
    response_labels: List[TextBoundingBox],
) -> List[Label]:
    """
    Extract text content from a list of labeled bounding boxes.

    This function processes a list of text bounding boxes, typically generated by an OCR system, and constructs a corresponding list of Label objects. Each Label encapsulates the text content and spatial coordinates of the original bounding box. The function assumes that the text content is already available in the input labels and does not perform OCR itself.

    The extracted labels are used for downstream processing such as text analysis, layout parsing, or data extraction.

    Parameters
    ----------
    response_labels : List[TextBoundingBox]
        A list of bounding boxes containing text regions detected by OCR. Each bounding box includes coordinates and the recognized text.

    Returns
    -------
    List[Label]
        A list of Label objects, each representing a text region with its associated text and spatial coordinates (y1, x1, y2, x2).

    Raises
    ------
    None
        This function does not raise exceptions under normal operation. Any errors during label construction are expected to be handled at the caller level.

    """
    labels = []
    for label in response_labels:
        labels.append(
            Label(
                text=label.text,
                y1=label.bbox_2d[y1_i],
                x1=label.bbox_2d[x1_i],
                y2=label.bbox_2d[y2_i],
                x2=label.bbox_2d[x2_i],
            )
        )
    return labels
